export const NEXT_PACKAGE_MARKER = 255;
export const MAX_PACKAGE_LENGTH_BYTES = 128;
export const MAX_FUNCTION_CALL_MESSAGE_LENGTH_BYTES = MAX_PACKAGE_LENGTH_BYTES;
export const MAX_FUNCTION_RETURN_MESSAGE_LENGTH_BYTES = MAX_PACKAGE_LENGTH_BYTES - 2;

export enum MESSAGE_POSITIONS {
  functionNum,
  functionsArgs,
}
