FROM amd64/node:13.7.0

COPY build/updater-arm/ app/
COPY updater/start.js app/start.js

ENV WORK_DIR="/app/data" PUID=1000 PGID=1000 LOG_LEVEL="" MQTT_BROKER_HOST="" MQTT_BROKER_PORT="" IOSERVER_MODE=false

WORKDIR /app

RUN npm install;
RUN npm install serialport;

VOLUME ["/app/data"]
EXPOSE 8087/tcp 8088/tcp 8089/tcp
CMD [ "node", "start.js" ]
